name: Build Firmware

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabihf

    - name: Build firmware
      run: |
        cd firmware
        chmod +x build.sh
        ./build.sh
        ls -lh fortress

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: firmware/fortress
